// Package auth implements token-backed API auth (TDR 022) — token
// generation/hashing, storage, bootstrap, and the HTTP middleware that
// enforces it.
package auth

import (
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
)

const tokenPrefix = "opusflow_pt_"

// GenerateToken returns a new random pairing token, high-entropy enough
// (32 random bytes) that brute-forcing it isn't a practical concern —
// which is what lets HashToken use a fast, unsalted hash instead of a
// deliberately-slow password hash (see HashToken).
func GenerateToken() (string, error) {
	b := make([]byte, 32)
	if _, err := rand.Read(b); err != nil {
		return "", fmt.Errorf("generating token: %w", err)
	}
	return tokenPrefix + hex.EncodeToString(b), nil
}

// HashToken hashes a token for storage/comparison. Unlike a password hash
// (bcrypt/argon2, deliberately slow, per-record salted to defend against
// dictionary/rainbow-table attacks on low-entropy human-chosen secrets),
// tokens are pre-generated by GenerateToken at high entropy — there's no
// dictionary to defend against, so a plain fast hash is both sufficient
// and lets validation do a single indexed lookup instead of comparing an
// incoming token against every stored row.
func HashToken(token string) string {
	sum := sha256.Sum256([]byte(token))
	return hex.EncodeToString(sum[:])
}
